### PR TITLE
Fix Issue 143 - Comboboxes scrolling when not expanded

### PR DESCRIPTION
**Pull request by Tiomat85**
Added an overridden handler for the scrollwheel to remove the situation where the scrollwheel was attemping to scroll comboboxes when they were not expanded.

### CODE REVIEW

**Comment by cmeyer** [comment]
This looks like a good solution...

Is this marked as 'draft' for a reason?

This will also need an update in `nionui-tool`. I can do that part.

**Comment by Tiomat85** [comment]
Short answer is the bit you spotted there, it worked fine in the debug QT mode but in the nionui-tool mode it didn't work as the event wasn't propagated into Python so while I have changed the bits in the nionui-tool c++ bit fine to pass on the event, but I didn't get time to figure out the build procedure part of it

**Comment by cmeyer** [comment]
The definitive build steps for `nionui-tool` are here (for the GitHub action):
https://github.com/nion-software/nionui-tool/blob/master/.github/workflows/build.yml

Similar build steps for the installer here:
https://github.com/nion-software/nionswift-installer/blob/master/.github/workflows/installer_win.yml

Also, since they're different repositories, they'll be two different PR's. I'll evaluate them together once they're both available.

**Comment by cmeyer** [comment]
Note: Once you successfully build `nionui-tool`, you will still need to explicitly launch the .exe file with the appropriate command line. You can see how this is done in the `nionui` module here:
https://github.com/nion-software/nionui/blob/a7eff31fa7dd807b9ddb2cb439c051d1796c578f/nionui/__main__.py#L67-L72

Your command line will look something like:
`C:\Path\To\NionLauncher.exe C:\Path\To\miniconda3\envs\YourEnvironment nionui_app.nionswift`

**Comment by Tiomat85** [comment]
https://github.com/nion-software/nionui-tool/pull/61 has gone in with the equivalent change in the uitool.

**Comment by cmeyer** [comment]
Merged here 92713a568ef75c438292d721a9df19d2cdfc4deb

**Pull request closed without merging**
